{
 "title": "Flow efficiency board",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Squad",
    "query": "CRM, Checkout, Mobile  , Devops, Open Standard, Yape Promos, Marketplace Platform, Tap2Phone, Remesas, Tipo de cambio, Data Strategy "
   },
   {
    "name": "q",
    "label": "Q",
    "query": "21.4, 22.1, 22.2, 22.3, 22.4, 23.1"
   },
   {
    "name": "tribe",
    "label": "Tribu",
    "query": "TI, Producto, Experiencia, Data"
   }
  ]
 },
 "panels": [
  {
   "title": "Eficiencia de Flujo - Squad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_sprint AS \"time\",\n  flow_efficiency, \n  team\nFROM _tool_google_spreadsheet\nwhere team in ($team)\nORDER BY 1, team"
    }
   ]
  },
  {
   "title": "Eficiencia de Flujo - Filtro de Squad, Q Y Tribu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_sprint AS \"time\",\n  flow_efficiency, \n  team\nFROM _tool_google_spreadsheet\nWHERE\n  1 = 1\n  AND\n  (team in ($team))\n  AND\n  (q in ($q))\n  AND\n  (tribe in ($tribe))\nORDER BY 1, team, q"
    }
   ]
  },
  {
   "title": "Eficiencia de Flujo - Tabla - prueba",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(end_sprint) AS \"time\",\n  CAST(sprint as DECIMAL) as sprint,\n  flow_efficiency,\n  team\nFROM _tool_google_spreadsheet\nWHERE team IN ($team)\nORDER BY team, end_sprint"
    }
   ]
  },
  {
   "title": "Eficiencia de Flujo y Throughput - Squad, Q y Tribu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_sprint AS \"time\",\n  flow_efficiency,\n  team\nFROM _tool_google_spreadsheet\nwhere\n  1 = 1\n  AND\n  (team in ($team))\n  AND\n  (q in ($q))\n  AND\n  (tribe in ($tribe))\nORDER BY 1, team"
    },
    {
     "rawSql": "SELECT\n  end_sprint AS \"time\",\n  throughput,\n  team\nFROM _tool_google_spreadsheet\nwhere\n\n  1 = 1\n  AND\n  (team in ($team))\n  AND\n  (q in ($q))\n  AND\n  (tribe in ($tribe))\nORDER BY 1, team"
    }
   ]
  },
  {
   "title": "Promedios de Eficiencia de Flujo - Filtro de Squad, Q Y Tribu",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  team,\n  avg(flow_efficiency)\nFROM _tool_google_spreadsheet\nWHERE \n  1 = 1\n  AND\n  (team in ($team)) \n  AND\n  (q in ($q))\n  AND\n  (tribe in ($tribe))\nGROUP BY team"
    }
   ]
  },
  {
   "title": "Throughput - Squad, Q y Tribu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_sprint AS \"time\",\n  throughput, \n  team\nFROM _tool_google_spreadsheet\nwhere\n1 = 1\n  AND\n  (team in ($team))\n  AND\n  (q in ($q))\n  AND\n  (tribe in ($tribe))\nORDER BY 1, team"
    }
   ]
  }
 ]
}